theme: jekyll-theme-slate
title: "DevQuest 2024"
description: "DevQuest is an international hackathon organized under the tertiary category of CODEFEST, aimed at showcasing the unique talents, creativity, and innovations of undergraduates from universities and institutes worldwide."
encoding: UTF-8